xunhuang/covid-19

website/src/Header.js, website/src/USCountyInfo.js
=> Add States to the search bar

website/src/USCountyInfo.js, website/src/USInfoTopWidget.js
messed up local repo, redid it, excluding all config files
=> Add "Last Updated" stamp under the summary tabs

website/src/GraphNewCases.js
Thus it's easier to see the trend of new cases and deaths.
=> Support hiding any of the three lines

website/src/GraphNewCases.js
=> Support horizontal reference lines in new cases graph

website/src/GraphNewCases.js
And I reordered the options by putting at the front what I think are more commonly used.
- Total
- New
- Death
- 2 Weeks
- Log
Feel free to reorder them if you think differently.
=> Move graph options to a drop-down menu

website/src/App.js
Thus it's easier for search engines to find the page.
My English may be not good enough. Feel free to change the wording.
=> Support changing page title

package-lock.json, website/package.json, website/src/GraphNewCases.js, website/src/TrendFitting.js
Used https://simplestatistics.org/docs/ to calculate linear regression
Demos
**if there are too few data, then we won't show it**
=> Trending Line and Day to Double

website/src/GraphNewCases.js
=> Change symbol for footnote on trend fitting

website/src/ListAllStates.js, website/src/PageUS.js, website/src/Util.js
For issue #36.
One problem: sorting doesn't work well and I was unable to fix it. @xunhuang could you help debug it?
=> Add States Testing table

website/src/Header.js
Add text "Like our site? Support us!" on the same line as "Discussions".
=> Add a link to donation page

website/src/Header.js
Add padding to search bar so it does not go all the way to the edge of the screen
=> Add padding to search bar to create space from edge of the browser

website/src/CovidUI.js, website/src/Map.js, website/src/PageCounty.js, website/src/PageMetro.js, website/src/PageState.js, website/src/PageUS.js, website/src/Theme.js, website/src/USInfoTopWidget.js, website/src/UnitedStates.js, website/src/graphs/GraphDaysToDoubleOverTime.js, website/src/graphs/GraphNewCases.js, website/src/graphs/Graphs.js, website/src/graphs/Summary.js
This is on top of #77 so should probably merge that first.
=> Reorganize tabs and fold the summary header into the first tab.

website/src/graphs/Graphs.js
Not sure if there is a better way to do this, but I know GitHub could certainly display this diff in a less awful way...
=> Make the graph section update when the history changes.

website/src/MapCountyGeneric.js, website/src/MapStateGeneric.js, website/src/MapUS.js
I think some of these are too washed out, but really having trouble telling at the moment. This code is pretty messy, didn't spend any time cleaning it up.
Most of the really dark counties on days to double are at negative infinity days to double. Maybe we should filter those.
=> Playing with the colors and lines on the map, curious what you think

website/src/App.js, website/src/MapUS.js
Fix:
1) once you're on an error page, it's inescapable and never rerenders even if the URL changes
2) if you're on the confirmed map, and you click confirmed again, everything breaks
3) if you're on the test coverage map and you go to the state tab, everything breaks
=> More error handling

website/src/USInfoTopWidget.js, website/src/UnitedStates.js
Wherein the girl who hates inheritance uses inheritance
=> Only have one summary method

website/src/Page404.js, website/src/PageCounty.js, website/src/PageMetro.js, website/src/PageState.js, website/src/PageUS.js, website/src/USInfoTopWidget.js, website/src/UnitedStates.js, website/src/graphs/Graphs.js
This changes the behavior of the header tags slightly: it will show "United States" if there is space, but will break it down to "US" when needed.
=> Fix places without counties

website/src/graphs/GraphNewCases.js
=> Show trending line label as legend

website/package.json, website/src/App.js, website/src/AppModule.js, website/src/ContentWrapping.js, website/src/CreditHover.js, website/src/Footer.js, website/src/Header.js, website/src/Page404.js, website/src/PageCounty.js, website/src/PageMetro.js, website/src/PageState.js, website/src/PageUS.js, website/src/Routes.js, website/src/graphs/DataCredit.js
=> New footer creation PR, now rebased

website/src/App.js, website/src/CreditHover.js, website/src/Footer.js, website/src/FooterDialogue.js, website/src/graphs/DataCredit.js
TODO: make the pop-ups dialogues instead of Popover components
=> Making data credit a popup & changing footer link functionality

website/src/DateRangeSlider.js, website/src/Util.js, website/src/graphs/GraphAxisScales.js, website/src/graphs/GraphDaysToDoubleOverTime.js, website/src/graphs/GraphNewCases.js, website/src/graphs/GraphRecoveryAndDeath.js
=> Add Date-Slider to graphs, replacing '2-weeks' toggle

website/src/Footer.js, website/src/graphs/DataCredit.js
Some of my additions earlier added more junk to the console. Removing those errors by fixing the props
=> Fixing erroneous console.log errors due to bad props

website/src/components/graphs/AdvancedGraph.js, website/src/components/tables/DivisionTable.js, website/src/components/tables/SortableTable.js, website/src/graphs/DataCredit.js, website/src/models/BasicDataComponent.js, website/src/models/DataSeries.js, website/src/models/Earth.js, website/src/models/PopulationComponent.js, website/src/models/World.js, website/src/pages/PageRegion.js, website/world_data_gen.js
Fix missing UK data (sorry for aggressive change, I tried to fix the old script for a few hours but couldn't figure it out...) and add percent change and days 2x to the tables. Changed graph to show 3-day average. Also made loading much faster.
=> Lots of changes to the world stuff

website/package.json, website/src/App.js, website/src/Footer.js, website/src/components/chrome/SearchInput.js, website/src/components/tables/DivisionTable.js, website/src/components/tables/SortableTable.js, website/src/models/Earth.js, website/src/models/SearchIndexComponent.js, website/src/models/World.js, website/src/pages/PageRegion.js
* search box
* highlighted the additional numbers you suggested in the top bar
* tweak the graphs into something more useful
* fixed the mobile layout
=> Add a search box and a bunch of other nonsense

website/src/App.js, website/src/GeoLocation.js, website/src/SearchBox.js, website/src/components/chrome/SearchInput.js, website/src/pages/PageRegion.js
**TODO:** Add function to find the user's country code based on their coordinates. If it's the US, then use it to find their county.
Contributes to #121 and closes #100
=> Adding ask to user for location & adding button to ROW search box

website/src/GeoLocation.js, website/src/components/chrome/SearchInput.js, website/src/models/Countries.js
The final changes that @aschleck requested.
Sorry @xunhuang , intended to address those last comments but didn't get a chance yesterday.
=> Addressing final minor comments from location PR

website/src/components/chrome/AppBar.js, website/src/components/chrome/SearchInput.js, website/src/components/graphs/AdvancedGraph.js, website/src/models/DataSeries.js, website/src/pages/PageRegion.js, website/world_data_gen.js
The colors are problematic but not quite sure how to make it better. I think I should allow different types of stippling to distinguish, but colors seem nicer. No idea.
=> Allow comparing locations
